common:
  asset_host: http://127.0.0.1:3000
  aws_s3:
    access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
    bucket_name: <%= ENV['AWS_S3_BUCKET_NAME'] %>
  branch_name: <%= ENV["BRANCH_NAME"] %>
  devise:
    secret_key: <%= ENV['DEVISE_KEY'] || SecureRandom.hex(64) %>
  honeybadger_api_key: <%= ENV['HONEYBADGER_API_KEY'] %>
  host: <%= ENV['APP_URL'] || ENV['HEROKU_URL'] || 'http://localhost:3000' %>
  log_level: debug
  mailer:
    default_from_email: "'Jumpstart' <notifications@wheel.com>"
    delivery_method: test
    smtp_settings:
      user_name: <%= ENV['MANDRILLAPP_USERNAME'] %>
      password: <%= ENV['MANDRILLAPP_PASSWORD'] %>
      address: smtp.mandrillapp.com
      port: 587
      authentication: plain
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  segmentio_write_key: BJbG3LZ42JVAxSpi5Rq5g3woCEOUCpix
  subject_prefix_for_outgoing_emails: JUMPSTART
  support_email:
    support@example.com
  stripe:
    publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
    secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>
  twilio:
    account_sid: <%= ENV['TWILIO_ACCOUNT_SID'] %>
    auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>
    from_number: <%= ENV['TWILIO_FROM_NUMBER'] %>

development:
  intercept_and_forward_emails_to:
    - john@example.com
    - adam@example.com
  mailer:
    delivery_method: :smtp

test:
  intercept_and_forward_emails_to:
    - john@example.com
    - adam@example.com
  mailer:
    delivery_method: :test

staging:
  <% heroku_url = ENV['HEROKU_URL'] || 'http://jumpstart-staging.herokuapp.com' %>
  <% heroku_host = URI(heroku_url).host %>
  host: <%= heroku_host %>
  intercept_and_forward_emails_to:
    - john@example.com
    - adam@example.com
  mailer:
    delivery_method: :smtp
    smtp_settings:
      user_name: <%= ENV['MANDRILLAPP_USERNAME'] %>
      password: <%= ENV['MANDRILLAPP_PASSWORD'] %>
      domain: www.wheel.com
      address: smtp.mandrillapp.com
      port: 587
      authentication: plain
      enable_starttls_auto: true
  support_email:
    support@example.com
  url_with_port: <%= heroku_url %>

production:
  bcc: hello.wheel@gmail.com
  host: jumpstart.com
  mailer:
    delivery_method: :smtp
    smtp_settings:
      user_name: <%= ENV['MANDRILLAPP_USERNAME'] %>
      password: <%= ENV['MANDRILLAPP_PASSWORD'] %>
      domain: www.wheel.com
      address: smtp.mandrillapp.com
      port: 587
      authentication: plain
      enable_starttls_auto: true
  support_email:
    support@example.com
  url_with_port: http://jumpstart.com
